name: Ruby

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ruby/setup-ruby@v1.123.0
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run:
        bundle exec rake
      env:
        TOKEN: ${{ secrets.HUGO_DUTY_TOKEN }}
        REPO: ${{ github.repository }}     

