name: Ruby

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: |
        bundle exec rake
      env:
        TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}     

