name: push md files to source branch
on:
  push:
    branches:
      - master
    paths:
      - docs/**
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_MD }}
      with:
        source_file: 'docs/*'
        destination_repo: 'ixxmu/ixxmu.github.io.source'
        destination_branch: 'main'
        destination_folder: 'content/post'
        user_email: 'jjliulangjj@gmail.com'
        user_name: 'ixxmu'
        commit_message: 'A custom message for the commit'
