name: push md files to source branch
on:
  workflow_run:
    workflows: ["generate a Markdown file"]
    types:
      - completed
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_MD }}
      with:
        source_file: 'posts'
        destination_repo: 'ixxmu/ixxmu.github.io.source'
        destination_branch: 'duty_others'
        destination_folder: 'content/'
        user_email: 'jjliulangjj@gmail.com'
        user_name: 'ixxmu'
        commit_message: 'A custom message for the commit'
        
    - name: Pushes test file to bk
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_MD }}
      with:
        source_file: 'posts'
        destination_repo: 'ixxmu/duty_bk'
        destination_branch: 'main'
        destination_folder: 'hugo_duty/'
        user_email: 'jjliulangjj@gmail.com'
        user_name: 'ixxmu'
        commit_message: 'A custom message for the commit'

    - name: Wait for file pushing
      run: sleep 10 & pwd

    - name: Delete Source Files
      run: |
        rm -rf posts # 删除源文件夹
      
    - name: Delete Source Files
      run: |
        echo "Deleting posts directory..."
        ls -alh # 打印当前目录结构以供检查
        rm -rf posts # 删除posts文件夹
        echo "After deletion:"
        ls -alh # 再次打印当前目录结构确认删除
      shell: bash
      
    - name: Commit and Push Deletion
      run: |
        git config --global user.email "jjliulangjj@gmail.com"
        git config --global user.name "ixxmu"
        git rm -rf posts
        git commit -m "Delete source posts folder"
        git push origin HEAD
      shell: bash
      
