name: push md files to source branch
on:
  workflow_run:
    workflows: ["generate a Markdown file"]
    types:
      - completed
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_MD }}
      with:
        source_file: 'posts'
        destination_repo: 'ixxmu/ixxmu.github.io.source'
        destination_branch: 'duty_others'
        destination_folder: 'content/'
        user_email: 'jjliulangjj@gmail.com'
        user_name: 'ixxmu'
        commit_message: 'A custom message for the commit'
